;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(paredit-forward-kill-word
                               ac-complete
                               paredit-forward-delete
                               beginning-of-visual-line
                               undo-tree-visualizer-quit
                               my-paredit-backward-kill-word))

(setq mc/cmds-to-run-once '(ac-previous
                            ac-next
                            paredit-backward-delete))

                            
                               